import { Internship } from '../types/Internship'

export const internships: Internship[] = [
  {
    _id: '1',
    title: 'Finance Intern',
    companyName: 'WealthGrow Pvt Ltd',
    description: 'Assist in financial analysis and reporting tasks.',
    location: 'Islamabad, Pakistan',
    durationWeeks: 12,
    stipend: '7000 PKR/month',
    requirements: ['MS Excel', 'Basic Accounting', 'Report writing'],
    mode: 'onsite',
    deadline: '2025-10-12',
    application: 'finance@wealthgrow.com',
  },
  {
    _id: '2',
    title: 'Frontend Developer Intern',
    companyName: 'TechNova Solutions',
    description:
      'Support in developing responsive UI components using React and Tailwind CSS.',
    location: 'Karachi, Pakistan',
    durationWeeks: 10,
    stipend: '8000 PKR/month',
    requirements: ['HTML', 'CSS', 'JavaScript', 'React'],
    mode: 'hybrid',
    deadline: '2025-11-01',
    application: 'frontend@technova.com',
  },
  {
    _id: '3',
    title: 'Backend Developer Intern',
    companyName: 'NextGen Software',
    description: 'Assist in building scalable APIs using Node.js and Express.',
    location: 'Lahore, Pakistan',
    durationWeeks: 8,
    stipend: '9000 PKR/month',
    requirements: ['Node.js', 'Express', 'MongoDB'],
    mode: 'onsite',
    deadline: '2025-11-15',
    application: 'backend@nextgen.pk',
  },
  {
    _id: '4',
    title: 'UI/UX Design Intern',
    companyName: 'PixelCraft Studio',
    description: 'Work on wireframes, mockups, and user flows for mobile apps.',
    location: 'Remote',
    durationWeeks: 6,
    stipend: '5000 PKR/month',
    requirements: ['Figma', 'Wireframing', 'Prototyping'],
    mode: 'remote',
    deadline: '2025-10-20',
    application: 'design@pixelcraft.io',
  },
  {
    _id: '5',
    title: 'Mobile App Intern',
    companyName: 'Appify Labs',
    description: 'Assist in developing cross-platform apps with Flutter.',
    location: 'Karachi, Pakistan',
    durationWeeks: 12,
    stipend: '10000 PKR/month',
    requirements: ['Dart', 'Flutter', 'Firebase'],
    mode: 'hybrid',
    deadline: '2025-11-10',
    application: 'interns@appifylabs.com',
  },
  {
    _id: '6',
    title: 'Data Science Intern',
    companyName: 'DataBridge Analytics',
    description:
      'Perform data cleaning, visualization, and assist in ML model training.',
    location: 'Lahore, Pakistan',
    durationWeeks: 14,
    stipend: '12000 PKR/month',
    requirements: ['Python', 'Pandas', 'Machine Learning basics'],
    mode: 'onsite',
    deadline: '2025-10-30',
    application: 'ds@databridge.com',
  },
  {
    _id: '7',
    title: 'Cybersecurity Intern',
    companyName: 'SecureTech Pvt Ltd',
    description:
      'Assist in penetration testing, vulnerability scanning, and SOC monitoring.',
    location: 'Islamabad, Pakistan',
    durationWeeks: 10,
    stipend: '11000 PKR/month',
    requirements: ['Networking basics', 'Linux', 'Security tools'],
    mode: 'onsite',
    deadline: '2025-11-12',
    application: 'security@securetech.com',
  },
  {
    _id: '8',
    title: 'Cloud Computing Intern',
    companyName: 'CloudWare Systems',
    description: 'Work with AWS services and assist in cloud deployment tasks.',
    location: 'Remote',
    durationWeeks: 8,
    stipend: '9000 PKR/month',
    requirements: ['AWS basics', 'Docker', 'Kubernetes'],
    mode: 'remote',
    deadline: '2025-11-05',
    application: 'cloud@cloudware.com',
  },
  {
    _id: '9',
    title: 'Marketing Intern',
    companyName: 'BrandHive Agency',
    description:
      'Support digital marketing campaigns and social media strategies.',
    location: 'Karachi, Pakistan',
    durationWeeks: 6,
    stipend: '6000 PKR/month',
    requirements: ['Content writing', 'SEO basics', 'Social media marketing'],
    mode: 'hybrid',
    deadline: '2025-10-25',
    application: 'marketing@brandhive.com',
  },
  {
    _id: '10',
    title: 'HR Intern',
    companyName: 'PeopleFirst Pvt Ltd',
    description:
      'Assist in recruitment processes, employee onboarding, and HR operations.',
    location: 'Lahore, Pakistan',
    durationWeeks: 8,
    stipend: '7000 PKR/month',
    requirements: ['Communication', 'MS Office', 'Teamwork'],
    mode: 'onsite',
    deadline: '2025-10-28',
    application: 'hr@peoplefirst.com',
  },
  {
    _id: '11',
    title: 'Content Writing Intern',
    companyName: 'WriteFlow Media',
    description:
      'Create engaging blog posts, social media content, and website copy.',
    location: 'Remote',
    durationWeeks: 6,
    stipend: '5000 PKR/month',
    requirements: ['English proficiency', 'Research skills', 'SEO writing'],
    mode: 'remote',
    deadline: '2025-11-07',
    application: 'content@writeflow.com',
  },
  {
    _id: '12',
    title: 'AI Research Intern',
    companyName: 'DeepMind Labs Pakistan',
    description: 'Assist in AI model training and research documentation.',
    location: 'Islamabad, Pakistan',
    durationWeeks: 16,
    stipend: '15000 PKR/month',
    requirements: ['Python', 'TensorFlow', 'Research skills'],
    mode: 'onsite',
    deadline: '2025-11-20',
    application: 'ai@deepmind.pk',
  },
  {
    _id: '13',
    title: 'Business Analyst Intern',
    companyName: 'Insight Consulting',
    description:
      'Support requirement gathering, process mapping, and business reports.',
    location: 'Karachi, Pakistan',
    durationWeeks: 10,
    stipend: '8000 PKR/month',
    requirements: ['MS Excel', 'Analytical skills', 'Documentation'],
    mode: 'hybrid',
    deadline: '2025-10-31',
    application: 'ba@insight.com',
  },
  {
    _id: '14',
    title: 'Game Development Intern',
    companyName: 'GameVerse Studios',
    description: 'Assist in Unity-based game development and testing.',
    location: 'Lahore, Pakistan',
    durationWeeks: 12,
    stipend: '10000 PKR/month',
    requirements: ['C#', 'Unity Engine', 'Problem solving'],
    mode: 'onsite',
    deadline: '2025-11-18',
    application: 'games@gameverse.com',
  },
  {
    _id: '15',
    title: 'Electrical Engineering Intern',
    companyName: 'ElectroTech Pvt Ltd',
    description:
      'Support circuit design, testing, and technical documentation.',
    location: 'Islamabad, Pakistan',
    durationWeeks: 14,
    stipend: '12000 PKR/month',
    requirements: ['Circuit design', 'MATLAB', 'PCB basics'],
    mode: 'onsite',
    deadline: '2025-11-11',
    application: 'ee@electrotech.com',
  },
  {
    _id: '16',
    title: 'Mechanical Design Intern',
    companyName: 'MechaWorks Ltd',
    description: 'Assist in CAD design and prototype testing.',
    location: 'Karachi, Pakistan',
    durationWeeks: 10,
    stipend: '9000 PKR/month',
    requirements: ['AutoCAD', 'SolidWorks', 'Problem solving'],
    mode: 'hybrid',
    deadline: '2025-10-29',
    application: 'design@mechaworks.com',
  },
  {
    _id: '17',
    title: 'Legal Intern',
    companyName: 'LawBridge Associates',
    description: 'Assist in legal research, drafting, and case preparation.',
    location: 'Lahore, Pakistan',
    durationWeeks: 8,
    stipend: '7000 PKR/month',
    requirements: ['Legal research', 'Drafting skills', 'Attention to detail'],
    mode: 'onsite',
    deadline: '2025-11-08',
    application: 'legal@lawbridge.com',
  },
  {
    _id: '18',
    title: 'Biotech Intern',
    companyName: 'Genomic Labs',
    description:
      'Support in lab experiments, data recording, and research assistance.',
    location: 'Islamabad, Pakistan',
    durationWeeks: 12,
    stipend: '11000 PKR/month',
    requirements: ['Lab techniques', 'Biology basics', 'Report writing'],
    mode: 'onsite',
    deadline: '2025-11-14',
    application: 'bio@genomiclabs.com',
  },
  {
    _id: '19',
    title: 'Graphic Design Intern',
    companyName: 'CreativeHub',
    description: 'Design social media posts, banners, and marketing materials.',
    location: 'Remote',
    durationWeeks: 6,
    stipend: '6000 PKR/month',
    requirements: ['Adobe Photoshop', 'Illustrator', 'Creativity'],
    mode: 'remote',
    deadline: '2025-10-26',
    application: 'design@creativehub.com',
  },
  {
    _id: '20',
    title: 'Journalism Intern',
    companyName: 'Daily Insight News',
    description:
      'Assist in reporting, article writing, and editing news content.',
    location: 'Karachi, Pakistan',
    durationWeeks: 8,
    stipend: '7000 PKR/month',
    requirements: ['English writing', 'Research', 'Communication skills'],
    mode: 'onsite',
    deadline: '2025-11-09',
    application: 'editor@dailyinsight.com',
  },
]
