import { Project } from "../types/projectTypes";

export const sampleProjects: Project[] = [
  {
    _id: 1,
    projectTitle: "E-Commerce Platform",
    shortDescription: "A scalable online store with secure payments.",
    techStack: "Next.js, MongoDB, Tailwind",
    fileUrl: "/files/ecommerce.zip",
    category: "Business",
  },
  {
    _id: 2,
    projectTitle: "Portfolio Website",
    shortDescription: "A modern personal portfolio to showcase skills.",
    techStack: "React, CSS3",
    fileUrl: "/files/portfolio.zip",
    category: "Design",
  },
  {
    _id: 3,
    projectTitle: "Business Dashboard",
    shortDescription: "An analytics dashboard for business insights.",
    techStack: "Node.js, Express, Chart.js",
    fileUrl: "/files/dashboard.zip",
    category: "Business",
  },
  {
    _id: 4,
    projectTitle: "Chat Application",
    shortDescription: "Real-time chat with private and group messaging.",
    techStack: "Socket.io, Node.js, React",
    fileUrl: "/files/chatapp.zip",
    category: "Development",
  },
  {
    _id: 5,
    projectTitle: "Learning Management System",
    shortDescription: "A platform for online courses and assessments.",
    techStack: "Laravel, Vue.js, MySQL",
    fileUrl: "/files/lms.zip",
    category: "Business",
  },
  {
    _id: 6,
    projectTitle: "Blog Platform",
    shortDescription: "A CMS-style blog with user authentication.",
    techStack: "Django, PostgreSQL, Bootstrap",
    fileUrl: "/files/blog.zip",
    category: "Development",
  },
  {
    _id: 7,
    projectTitle: "Food Delivery App",
    shortDescription: "Order food online with real-time tracking.",
    techStack: "Flutter, Firebase",
    fileUrl: "/files/foodapp.zip",
    category: "Business",
  },
  {
    _id: 8,
    projectTitle: "Job Portal",
    shortDescription: "Platform for job seekers and recruiters.",
    techStack: "Next.js, Express, PostgreSQL",
    fileUrl: "/files/jobportal.zip",
    category: "Business",
  },
  {
    _id: 9,
    projectTitle: "Travel Booking System",
    shortDescription: "Book flights, hotels, and tours with ease.",
    techStack: "Spring Boot, Angular, MySQL",
    fileUrl: "/files/travel.zip",
    category: "Business",
  },
  {
    _id: 10,
    projectTitle: "Inventory Management",
    shortDescription: "Track and manage inventory efficiently.",
    techStack: "PHP, CodeIgniter, MySQL",
    fileUrl: "/files/inventory.zip",
    category: "Business",
  },
  {
    _id: 11,
    projectTitle: "Online Examination System",
    shortDescription: "Conduct exams securely with instant results.",
    techStack: "ASP.NET, SQL Server",
    fileUrl: "/files/exam.zip",
    category: "Business",
  },
  {
    _id: 12,
    projectTitle: "Fitness Tracking App",
    shortDescription: "Track workouts, diet, and health progress.",
    techStack: "React Native, Node.js, MongoDB",
    fileUrl: "/files/fitness.zip",
    category: "Development",
  },
  {
    _id: 13,
    projectTitle: "Music Streaming App",
    shortDescription: "Stream music with personalized playlists.",
    techStack: "Kotlin, Firebase",
    fileUrl: "/files/music.zip",
    category: "Development",
  },
  {
    _id: 14,
    projectTitle: "Weather Forecast App",
    shortDescription: "Get live weather updates and alerts.",
    techStack: "React, OpenWeather API",
    fileUrl: "/files/weather.zip",
    category: "Development",
  },
  {
    _id: 15,
    projectTitle: "Social Media Platform",
    shortDescription: "Connect with friends and share updates.",
    techStack: "MERN Stack",
    fileUrl: "/files/social.zip",
    category: "Development",
  },
  {
    _id: 16,
    projectTitle: "Hospital Management System",
    shortDescription: "Manage patients, staff, and appointments.",
    techStack: "Java, MySQL, JSP",
    fileUrl: "/files/hospital.zip",
    category: "Business",
  },
  {
    _id: 17,
    projectTitle: "Online Quiz App",
    shortDescription: "Play quizzes and compete with friends.",
    techStack: "Vue.js, Firebase",
    fileUrl: "/files/quiz.zip",
    category: "Design",
  },
  {
    _id: 18,
    projectTitle: "Expense Tracker",
    shortDescription: "Track personal income and expenses.",
    techStack: "React, Redux, Node.js",
    fileUrl: "/files/expense.zip",
    category: "Business",
  },
  {
    _id: 19,
    projectTitle: "Online Banking System",
    shortDescription: "Secure transactions and account management.",
    techStack: "C#, .NET Core, SQL Server",
    fileUrl: "/files/banking.zip",
    category: "Business",
  },
  {
    _id: 20,
    projectTitle: "Event Management App",
    shortDescription: "Plan and organize events effortlessly.",
    techStack: "Ionic, Firebase",
    fileUrl: "/files/event.zip",
    category: "Business",
  },
];
