import { Job } from '@/componants/types/Job'

export const dummyJobs: Job[] = [
  {
    _id: '1',
    title: 'Content Writer',
    role: 'Writer',
    company: 'WriteRight Media',
    location: 'Lahore, Pakistan',
    type: 'Full-time',
    mode: 'hybrid',
    salary: '40,000 - 60,000 PKR',
    tags: ['SEO', 'Blogging', 'Content'],
    experience: '1-2 years',
    description:
      'Create high-quality content for blogs, websites, and social media.',
    requirements: 'Excellent writing, SEO, Research skills, Blogging',
    application: 'jobs@writeright.com',
    sampleResume: '',
    deadline: '2025-10-18',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    _id: '2',
    title: 'Frontend Developer',
    role: 'Developer',
    company: 'Techify Solutions',
    location: 'Karachi, Pakistan',
    type: 'Contract',
    mode: 'remote',
    salary: '80,000 - 100,000 PKR',
    tags: ['React', 'Next.js', 'Tailwind'],
    experience: '2-3 years',
    description:
      'Work on frontend projects using React, Next.js, and Tailwind CSS.',
    requirements: 'Proficiency in React, Next.js, Tailwind, and Git.',
    application: 'hr@techify.com',
    sampleResume: '',
    deadline: '2025-11-05',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  // --- Repeat and modify for jobs 3 to 20 ---
  {
    _id: '3',
    title: 'Backend Developer',
    role: 'Developer',
    company: 'CodeMasters',
    location: 'Islamabad, Pakistan',
    type: 'Full-time',
    mode: 'onsite',
    salary: '70,000 - 90,000 PKR',
    tags: ['Node.js', 'Express', 'MongoDB'],
    experience: '2-4 years',
    description: 'Develop backend APIs and manage database operations.',
    requirements: 'Strong in Node.js, Express, MongoDB, REST APIs',
    application: 'jobs@codemasters.com',
    sampleResume: '',
    deadline: '2025-10-30',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    _id: '4',
    title: 'UI/UX Designer',
    role: 'Designer',
    company: 'DesignHive',
    location: 'Lahore, Pakistan',
    type: 'Full-time',
    mode: 'remote',
    salary: '50,000 - 70,000 PKR',
    tags: ['Figma', 'Adobe XD', 'Sketch'],
    experience: '1-3 years',
    description: 'Design engaging interfaces and prototypes for web apps.',
    requirements: 'Experience in Figma, Adobe XD, and UI design principles',
    application: 'careers@designhive.com',
    sampleResume: '',
    deadline: '2025-10-25',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    _id: '5',
    title: 'Data Analyst',
    role: 'Analyst',
    company: 'DataCorp',
    location: 'Karachi, Pakistan',
    type: 'Full-time',
    mode: 'hybrid',
    salary: '60,000 - 80,000 PKR',
    tags: ['Excel', 'SQL', 'Python', 'PowerBI'],
    experience: '1-2 years',
    description: 'Analyze business data and generate insights.',
    requirements: 'Strong in Excel, SQL, Python, PowerBI',
    application: 'hr@datacorp.com',
    sampleResume: '',
    deadline: '2025-11-10',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    _id: '6',
    title: 'Marketing Executive',
    role: 'Marketing',
    company: 'BrandBoost',
    location: 'Islamabad, Pakistan',
    type: 'Full-time',
    mode: 'onsite',
    salary: '45,000 - 60,000 PKR',
    tags: ['SEO', 'Content Marketing', 'Social Media'],
    experience: '1-2 years',
    description:
      'Plan and execute marketing campaigns across digital platforms.',
    requirements: 'Knowledge of SEO, social media, content marketing',
    application: 'jobs@brandboost.com',
    sampleResume: '',
    deadline: '2025-11-05',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    _id: '7',
    title: 'Full Stack Developer',
    role: 'Developer',
    company: 'Innovatech',
    location: 'Lahore, Pakistan',
    type: 'Full-time',
    mode: 'remote',
    salary: '90,000 - 120,000 PKR',
    tags: ['React', 'Node.js', 'MongoDB', 'Next.js'],
    experience: '3-5 years',
    description: 'Build scalable web applications from frontend to backend.',
    requirements: 'Proficiency in React, Node.js, MongoDB, Next.js, REST APIs',
    application: 'careers@innovatech.com',
    sampleResume: '',
    deadline: '2025-10-20',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    _id: '8',
    title: 'Graphic Designer',
    role: 'Designer',
    company: 'Creatix',
    location: 'Karachi, Pakistan',
    type: 'Contract',
    mode: 'remote',
    salary: '40,000 - 55,000 PKR',
    tags: ['Photoshop', 'Illustrator', 'Figma'],
    experience: '1-3 years',
    description:
      'Create visual designs for social media, web, and print media.',
    requirements: 'Experience in Photoshop, Illustrator, and Figma',
    application: 'jobs@creatix.com',
    sampleResume: '',
    deadline: '2025-10-28',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    _id: '9',
    title: 'HR Manager',
    role: 'HR',
    company: 'PeopleFirst',
    location: 'Islamabad, Pakistan',
    type: 'Full-time',
    mode: 'onsite',
    salary: '80,000 - 100,000 PKR',
    tags: ['HR', 'Recruitment', 'Employee Relations'],
    experience: '3-5 years',
    description: 'Manage HR operations, recruitment, and employee engagement.',
    requirements: 'Experience in HR management and recruitment',
    application: 'hr@peoplefirst.com',
    sampleResume: '',
    deadline: '2025-11-12',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    _id: '10',
    title: 'Mobile App Developer',
    role: 'Developer',
    company: 'AppWorks',
    location: 'Lahore, Pakistan',
    type: 'Full-time',
    mode: 'hybrid',
    salary: '75,000 - 95,000 PKR',
    tags: ['Flutter', 'React Native', 'iOS', 'Android'],
    experience: '2-4 years',
    description: 'Develop mobile applications for Android and iOS platforms.',
    requirements:
      'Experience with Flutter, React Native, iOS, and Android development',
    application: 'jobs@appworks.com',
    sampleResume: '',
    deadline: '2025-11-01',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  // --- Jobs 11 to 20 (repeat with small changes) ---
  {
    _id: '11',
    title: 'SEO Specialist',
    role: 'Marketing',
    company: 'RankHigh',
    location: 'Karachi, Pakistan',
    type: 'Full-time',
    mode: 'remote',
    salary: '50,000 - 70,000 PKR',
    tags: ['SEO', 'Analytics', 'Google Ads'],
    experience: '1-3 years',
    description: 'Optimize websites to improve search engine rankings.',
    requirements: 'Experience in SEO, Analytics, and Google Ads',
    application: 'jobs@rankhigh.com',
    sampleResume: '',
    deadline: '2025-10-22',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    _id: '12',
    title: 'Project Manager',
    role: 'Manager',
    company: 'BuildSmart',
    location: 'Hafizabad, Pakistan',
    type: 'Full-time',
    mode: 'onsite',
    salary: '100,000 - 120,000 PKR',
    tags: ['Management', 'Agile', 'Scrum'],
    experience: '4-6 years',
    description:
      'Manage software projects, timelines, and deliverables efficiently.',
    requirements: 'Experience in project management and Agile/Scrum',
    application: 'hr@buildsmart.com',
    sampleResume: '',
    deadline: '2025-11-15',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    _id: '13',
    title: 'Social Media Manager',
    role: 'Marketing',
    company: 'SocialBoost',
    location: 'Lahore, Pakistan',
    type: 'Full-time',
    mode: 'hybrid',
    salary: '45,000 - 60,000 PKR',
    tags: ['Social Media', 'Content Creation', 'Marketing'],
    experience: '2-4 years',
    description: 'Manage and grow social media accounts for clients.',
    requirements: 'Experience in social media management and marketing',
    application: 'jobs@socialboost.com',
    sampleResume: '',
    deadline: '2025-10-30',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    _id: '14',
    title: 'DevOps Engineer',
    role: 'Developer',
    company: 'CloudTech',
    location: 'Karachi, Pakistan',
    type: 'Full-time',
    mode: 'remote',
    salary: '90,000 - 110,000 PKR',
    tags: ['AWS', 'Docker', 'CI/CD'],
    experience: '3-5 years',
    description:
      'Maintain and automate cloud infrastructure and deployment pipelines.',
    requirements: 'Experience in AWS, Docker, CI/CD pipelines',
    application: 'hr@cloudtech.com',
    sampleResume: '',
    deadline: '2025-11-10',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    _id: '15',
    title: 'QA Engineer',
    role: 'QA',
    company: 'TestLab',
    location: 'Islamabad, Pakistan',
    type: 'Full-time',
    mode: 'onsite',
    salary: '60,000 - 80,000 PKR',
    tags: ['Testing', 'Automation', 'Selenium'],
    experience: '2-4 years',
    description:
      'Test software applications and ensure high quality standards.',
    requirements: 'Experience in manual and automated testing',
    application: 'jobs@testlab.com',
    sampleResume: '',
    deadline: '2025-11-05',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    _id: '16',
    title: 'Graphic Illustrator',
    role: 'Designer',
    company: 'CreativeMinds',
    location: 'Lahore, Pakistan',
    type: 'Contract',
    mode: 'remote',
    salary: '35,000 - 50,000 PKR',
    tags: ['Illustrator', 'Photoshop', 'Creative Design'],
    experience: '1-2 years',
    description: 'Create illustrations for web, print, and social media.',
    requirements: 'Experience in Illustrator, Photoshop, and creative design',
    application: 'jobs@creativeminds.com',
    sampleResume: '',
    deadline: '2025-10-28',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    _id: '17',
    title: 'Business Analyst',
    role: 'Analyst',
    company: 'BizSolutions',
    location: 'Karachi, Pakistan',
    type: 'Full-time',
    mode: 'hybrid',
    salary: '70,000 - 90,000 PKR',
    tags: ['Analysis', 'Reporting', 'Excel'],
    experience: '2-4 years',
    description: 'Analyze business processes and provide improvement insights.',
    requirements: 'Experience in business analysis and reporting',
    application: 'hr@bizsolutions.com',
    sampleResume: '',
    deadline: '2025-11-12',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    _id: '18',
    title: 'Frontend Designer',
    role: 'Designer',
    company: 'WebDesigners',
    location: 'Islamabad, Pakistan',
    type: 'Full-time',
    mode: 'remote',
    salary: '50,000 - 70,000 PKR',
    tags: ['React', 'Figma', 'CSS'],
    experience: '1-3 years',
    description: 'Design web pages and interfaces using React and Figma.',
    requirements: 'Experience in React, Figma, CSS, HTML',
    application: 'jobs@webdesigners.com',
    sampleResume: '',
    deadline: '2025-11-01',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    _id: '19',
    title: 'Technical Writer',
    role: 'Writer',
    company: 'DocuTech',
    location: 'Lahore, Pakistan',
    type: 'Full-time',
    mode: 'hybrid',
    salary: '45,000 - 60,000 PKR',
    tags: ['Writing', 'Documentation', 'Tech'],
    experience: '1-2 years',
    description: 'Write technical documentation and manuals.',
    requirements: 'Excellent technical writing skills',
    application: 'hr@docutech.com',
    sampleResume: '',
    deadline: '2025-10-20',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
  {
    _id: '20',
    title: 'Intern - Software Development',
    role: 'Internship',
    company: 'SoftIntern',
    location: 'Karachi, Pakistan',
    type: 'Part-time',
    mode: 'remote',
    salary: '15,000 - 25,000 PKR',
    tags: ['Internship', 'Software Development', 'React'],
    experience: 'No experience',
    description: 'Assist in software development projects.',
    requirements: 'Basic knowledge of programming',
    application: 'intern@softintern.com',
    sampleResume: '',
    deadline: '2025-11-05',
    status: 'Active',
    createdAt: '2025-09-01',
    updatedAt: '2025-09-01',
  },
]
